version: '3'
services:
  monitoring-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CATALINA_OPTS: >-
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888
        -Dcom.sun.management.jmxremote.rmi.port=8891
        -Dcom.sun.management.jmxremote.port=8891
        -Dcom.sun.management.jmxremote.host=0.0.0.0
        -Djava.rmi.server.hostname=0.0.0.0
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false  -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.local.only=false
      JAVA_OPTS: >-
        -XshowSettings:vm -XX:MinRAMPercentage=5 -XX:MaxRAMPercentage=80
        -XX:+HeapDumpOnOutOfMemoryError
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_NAME: '${DB_NAME}'
      DB_PORT: '${DB_PORT}'
      DB_HOST: '${DB_HOST}'
    restart: always
    ports:
      - '8080:8080'
      - '8888:8888'
      - '8891:8891'
    volumes:
      - './lmData:/root/.lm'
    depends_on:
      - mysql
    networks:
      test-app-network:
        aliases:
          - monitoring-api
  mysql:
    container_name: mysql
    image: 'mysql:5.7'
    restart: always
    volumes:
      - './sql:/docker-entrypoint-initdb.d'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_USER=${DB_USERNAME}'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
    networks:
      test-app-network:
        aliases:
          - mysql
  prometheus:
    container_name: prometheus
    restart: always
    image: prom/prometheus
    volumes:
      - ./src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      test-app-network:
        aliases:
          - prometheus
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      test-app-network:
        aliases:
          - grafana
networks:
  test-app-network: null