global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/monitoring-api/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['monitoring-api:8080']